---
- name: add in memory hosts
  hosts: all
  roles:
  - { name: openstack_add_host }
  
- name: Check website
  hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
     url: "http://{{ item }}"
     return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage
