---
- hosts: jumpbox
  roles:
  - { name: openstack_network_create }
  - { name: openstack_nova_flavor_create }
  - { name: openstack_network_sg_create }
  - { name: openstack_nova_keypair_create }
  - { name: openstack_nova_server_create }
  - { name: openstack_add_host }
