
  - name: remove router
    os_router:
      cloud: ospcloud
      state: absent
      name: router1


  - name: copy script to clean ports
    template:
      src: clean-ports.j2
      dest: /root/clean-ports.sh
      mode: 0755   

  - name: clean ports and networks
    shell: /root/clean-ports.sh
      
#  - name: remove internal subnet
#    os_subnet:
#      cloud: ospcloud
#      state: absent
#      name: internal_subnet
      
#  - name: remove internal network
#    os_network:
#      cloud: ospcloud
#      state: absent
#     name: int_network
     

