---
- name: deleting floating IP to Servers "{{ item.value.name }}"
  os_floating_ip:
    cloud: ospcloud
    state: absent
    server: "{{ item.value.name }}"
    network: ext_network
  with_dict: "{{osp_servers}}"
  
- name: delete instance "{{ item.name }}"
  os_server:
    cloud: ospcloud
    name: "{{ item.value.name  }}"
    state: absent
  with_dict: "{{osp_servers}}"

